# Generated by Django 2.1.5 on 2019-04-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_venda_nfe_emitida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('permissão 1', 'Permissão 1'), ('permissão 2', 'Permissão 2'))},
        ),
    ]
