# Generated by Django 2.1.5 on 2019-04-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_auto_20190403_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('permissão 2', 'Descrição da permissão 2'))},
        ),
    ]
