# Generated by Django 2.1.5 on 2019-02-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190215_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('endereço', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('data', models.DateField(verbose_name='DD-MM-YYYY')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
            ],
        ),
    ]
