# Generated by Django 2.1.5 on 2019-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20190215_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=5, null=True)),
                ('data_hora', models.DateTimeField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='pessoas',
            name='compra',
            field=models.ManyToManyField(blank=True, to='produtos.Compra'),
        ),
    ]
