# Generated by Django 2.1.5 on 2019-04-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20190215_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='Produto',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='compra',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
